dist: xenial

os: linux

arch: x86_64

language: python

python:
    - 3.8

services:
    - postgresql

before_script:
    # * please ALWAYS run "python manage.py makemigrations" before pushing to GitHub
    # * to ensure migration files are up-to-date
    - psql -c "CREATE DATABASE $RDS_DB_NAME;" -U postgres
    - psql -c "CREATE USER $RDS_USERNAME WITH ENCRYPTED PASSWORD '$RDS_PASSWORD';"
    - psql -c "ALTER DATABASE $RDS_DB_NAME OWNER TO $RDS_USERNAME;"
    - python manage.py migrate

install:
    - pip install -r requirements.txt

script:
    - black --check .
    - flake8 .
    - coverage run manage.py test

after_success:
    - coveralls

deploy:
    cleanup: false
    provider: elasticbeanstalk
    access_key_id: $AWS_EB_ACCESS_KEY
    secret_access_key: $AWS_EB_SECRET_ACCESS_KEY
    region: us-west-2
    app: mysite
    env: mysite-dev2
    bucket: $AWS_EB_BUCKET_NAME
    on:
        branch: main
