branch-defaults:
  master:
    environment: swe1-env
environment-defaults:
  swe1-env:
    branch: null
    repository: null
global:
  application_name: swe1-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
